### ISSUE TITLE
Default word's list

### ISSUE THREAD

**Issue by hontarenkoYana** [MrDogeBro/content_filter#9]
Is default word's list empty? 
Or maybe there is some option in your library to see the all list of words which will be filtered?

**Comment by MrDogeBro** [comment]
The default word list is not empty. The default word list is just a default profanity filter. If you would like to see the words in the default list, you could look through the default list file in the source code (https://github.com/MrDogeBro/content_filter/blob/master/content_filter/data/filter.json).

**Comment by hontarenkoYana** [comment]
@MrDogeBro , oh, I see now!
Thank you for the answering! Amazing tool :)

**Comment by MrDogeBro** [comment]
@hontarenkoYana no problem. Glad to help.
